In [5]:
#Task 1
#question 1

def compute(a,b):
    try:
        c=a/b
        return c
    except ZeroDivisionError:
        print("Oops!  not a valid operation")
compute(5,0)


Oops!  not a valid operation


In [14]:
#question 2
def listToString(s):  
    
    # initialize an empty string 
    str1 = " " 
    
    # return string   
    return (str1.join(s)) 
subjects=[['Americans'],['Indian']]
verbs=[['play'],['watch']]
objects=[['Baseball'],['Cricket']]

for sub in subjects:
    for ver in verbs:
        for obj in objects:
            print(listToString(sub)+" "+listToString(ver)+" "+listToString(obj))

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indian play Baseball
Indian play Cricket
Indian watch Baseball
Indian watch Cricket


In [13]:
#task 2
#question 1
def matpower(arr,N):
    import numpy as np
    return np.array([x**(N-1-i) for i in range(N)])

x = np.array([1, 2, 3, 5])
N = 3
matpower(x,N)

array([[ 1,  4,  9, 25],
       [ 1,  2,  3,  5],
       [ 1,  1,  1,  1]], dtype=int32)

[array([ 1,  4,  9, 25], dtype=int32),
 array([1, 2, 3, 5], dtype=int32),
 array([1, 1, 1, 1], dtype=int32)]

[1 1 1 1]
[1 2 3 5]
[ 1  4  9 25]
